spring:
  application:
    name: finance-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/mojhome-f0f0a

server:
  port: 8200

logging:
  level:
    it:
      sosinski: DEBUG