spring:
  application:
    name: finance-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8100/auth/realms/mojhome

server:
  port: 8200

logging:
  level:
    it:
      sosinski: DEBUG